apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
spec:
    type: NodePort
    selector:
        app: app
    ports:
     - protocol: TCP
       port: 3000
       targetPort: 3000
       nodePort: 30080
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "helm.fullname" . }}
#   labels:
#     {{- include "helm.labels" . | nindent 4 }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: TCP
#       name: http
#   selector:
#     {{- include "helm.selectorLabels" . | nindent 4 }}
