name: Helm CI/CD for Home Lab

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.8.0

    - name: Lint Helm Chart
      run: helm lint helm-charts/myapp

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Configure kubectl
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
        echo "KUBECONFIG=kubeconfig" >> $GITHUB_ENV

    - name: Deploy to Home Lab Kubernetes
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      run: |
        helm upgrade --install myapp helm-charts/myapp --namespace default --set image.repository=dpentim78/oteemo-app
