name: Helm CI/CD for Home Lab

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: Check Helm installation
      run: |
        if ! command -v helm &> /dev/null; then
          echo "Helm is not installed. Please install Helm on your self-hosted runner."
          echo "Visit https://helm.sh/docs/intro/install/ for installation instructions."
          exit 1
        fi
        helm version

    - name: Lint Helm Chart
      run: helm lint helm-charts/myapp

    - name: Verify kubectl configuration
      run: |
        if ! kubectl get nodes; then
          echo "Error: Unable to connect to the cluster."
          kubectl config view
          exit 1
        else
          echo "Successfully connected to the cluster"
        fi

    - name: Deploy to Home Lab Kubernetes
      run: |
        if ! helm upgrade --install myapp helm-charts/myapp --namespace default --set image.repository=dpentim78/oteemo-app --debug; then
          echo "Error: Helm deployment failed. Here's some debug information:"
          helm ls --all-namespaces
          kubectl get pods --all-namespaces
          exit 1
        fi
